var a = 11;
var b = 5;
var c = a % b;
console.log(c);
console.log(".......");
console.log(a+b);
--a;
console.log(a+b);
console.log("assignment operators");
var m = 2;
var n = 3;
var l = 2**3;
console.log(l);
l**=m;
console.log(l);