var Name = "Hello world";
console.log(Name);
console.log(Name);
console.log(Name);
console.log(Name);
console.log(Name);
console.log(Name);
console.log(Name);
console.log(Name);
console.log(Name);
console.log(Name);